Add `net5` and `net6` as TargetFrameworks
Handlebars-Net/Handlebars.Net pull request #479
Opened 2021-12-19 00:47 UTC by zjklee

2024-03-31 21:49 UTC, thompson-tomo requested changes

2024-03-31 21:49 UTC, thompson-tomo commented on source/Handlebars/Handlebars.csproj
> +
Microsoft.CSharp is a polyfill package hence this dependency should be able to be removed on the newer frameworks.

2024-03-31 22:12 UTC, thompson-tomo commented
Closes #573

2024-04-01 01:08 UTC, thompson-tomo commented
@oformaniuk & @StefH I see that this has been sitting around for a while, any chance could the conflicts be resolved and then this merge progressed. :)

2024-04-01 01:32 UTC, oformaniuk commented
> @oformaniuk & @StefH I see that this has been sitting around for a while, any chance could the conflicts be resolved and then this merge progressed. :)

I'd be happy to handle merging part if you can handle conflicts :)

2024-04-01 05:02 UTC, thompson-tomo requested changes

2024-04-01 05:02 UTC, thompson-tomo commented on source/Handlebars.Test/Handlebars.Test.csproj
> +
Should be checked if this is really needed.

2024-04-01 05:05 UTC, thompson-tomo commented
@oformaniuk I will take a look later today to see if I can push changes to this branch.

2024-04-01 05:14 UTC, oformaniuk commented
> @oformaniuk I will take a look later today to see if I can push changes to this branch. 

If not, it can be done by forking and merging back to this branch via PR 🙂

2024-04-01 06:34 UTC, thompson-tomo commented
@oformaniuk pr #577 has been created to resolve the conflicts and implements the feedback i have above.

2024-04-01 08:37 UTC, StefH commented
@thompson-tomo and @oformaniuk 
I think it's more clear that this PR is just closed and a new PR is created which only adds the new frameworks.

Side note: do we actually want to add .NET 5 because that one is out of support for some time? And instead just add .NET 6 and .NET 8 because .NET 7 is also almost out of official support?

2024-04-01 09:16 UTC, thompson-tomo commented
@StefH i agree. What I will do tomorrow morning my time is cherry pick the commits on to a new branch from master & then submit that as a fresh pr & close my other pr.

2024-04-01 16:09 UTC, closed without merging

2024-04-01 16:09 UTC, oformaniuk commented
As agreed, change will be handled in a new PR.

2024-04-01 20:52 UTC, thompson-tomo commented
New PR is #578 which is a nice and clean PR.