Add optional 3rd argument to lookup helper
Handlebars-Net/Handlebars.Net pull request #542
Opened 2023-02-21 09:00 UTC by StefH

2023-02-22 01:55 UTC, zjklee requested changes

2023-02-22 08:07 UTC, StefH commented on source/Handlebars.Test/BasicIntegrationTests.cs
> -using Xunit;
I did revert some changes. however some changes happened automatically in Visual Studio when I just saved the file.

You know that in GitHub review you can hide whitespaces?
![image](https://user-images.githubusercontent.com/249938/220559848-452caad3-a255-4e35-b8bd-ac90b8a58d74.png)

2023-02-23 20:14 UTC, zjklee approved these changes

2023-02-23 20:14 UTC, merged

2023-02-23 20:36 UTC, StefH commented
@zjklee 
Thanks for merging.
(BTW I always use Squash-Commit when merging a PR to master, else you see all the individual commits which do not add that much value and the branch tree-view looks a bit cleaner)

Any idea when a new NuGet will be released?